FROM fluentd:v1.16.2-debian-1.1
USER root
RUN echo "source 'https://mirrors.tuna.tsinghua.edu.cn/rubygems/'" > Gemfile && gem install bundler

RUN apt update \
    && apt install -y python3 python3-pip \
    && ln -s /usr/bin/python3 /usr/bin/python

